### PR TITLE
fix #149 #150

### LINKED ISSUE #149: Netherite mesh should be made from emerald mesh
**Describe the bug**
Netherite mesh is made from diamond mesh instead of emerald mesh. This is not the expected progression.

**To Reproduce**
n/a
**Expected behavior**
Make netherite mesh from emerald mesh instead of diamond mesh.

**Screenshots**
n/a

**Version**
Minecraft Version: 1.16.5
Forge Version: 36.0.42
Ex Nihilo: Sequentia Version: 1.16-2.0.2.3

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by remplerus**
actually, i dont think crying obsidian needs to be implemented, but i included it with waterbucket and obsidian as recipe
hopefully i have done that all correctly this time

### CODE REVIEW

**Comment by remplerus** [comment]
i used the stone pebble as template for basalt and blackstone pebble

**Comment by remplerus** [comment]
added ancient debris

**Comment by Blackout03** [comment]
ancient debris seems expensive, if you want to change it back to scraps from debris you lose 7 scraps

**Comment by remplerus** [comment]
well scraps you can sieve but you cant get debris without a nether :)

**Comment by NovaMachina** [comment]
Is there any reason allow the crafting of ancient debris?

**Comment by remplerus** [comment]
dont think so, only reason i could say is, you cant get the block itself, if you want to build with it.

**Review by NovaMachina — APPROVED** [review]
I agree that ancient debris are expensive, but for now I'll merge it in and we can balance it later.

**Pull request merged**
