### PR TITLE
Create sv_se.json

### PR DESCRIPTION
**Pull request by Regnander**
Thanks for an interesting mod!

I translated `block.exnihilosequentia.infesting_leaves` as "Half-infested leaves", since I couldn't find a way to translate it without making it sound weird.

### CODE REVIEW

**Review by NovaMachina — APPROVED** [review]

**Comment by ghost** [comment]
Which name you want to use for translation credits?
Everyone who translated the mod gonna be listed as translator

**Comment by Regnander** [comment]
> Which name you want to use for translation credits? Everyone who translated the mod gonna be listed as translator

"Regnander" works for me.

**Comment by ghost** [comment]
If you got a discord account, we can add you in the contributor list

**Comment by Regnander** [comment]
> If you got a discord account, we can add you in the contributor list

I do, but I'd rather not post my Discord username publicly.

**Comment by ghost** [comment]
if you got a discord server where i can find you on or private message on github

**Comment by Regnander** [comment]
I just posted my username on this Pastebin, so just tell me when you got it and I will delete it: https://pastebin.com/q5HSDzis

**Pull request merged**
