### PR TITLE
fix crt remove by input doesn't work

### PR DESCRIPTION
**Pull request by friendlyhj**
Simply overriding `IRecipe#getIngredients` will solve the issue (#312). This PR only fixes the issue in 1.18 version. For 1.16 and the future version (1.19), I hope the author of this repo fixes it. (just don't want to make 3 PRs with the same content)

### CODE REVIEW

**Review by remplerus — APPROVED** [review]

**Review by NovaMachina — APPROVED** [review]

**Comment by NovaMachina** [comment]
Due to recent issues with the build pipeline, the SonarQube checks had to be rebuilt and thus a new project key generated. Please update the following section of `build.gradle` so that this build will pass.

```groovy
sonarqube {
    properties {
        property "sonar.projectKey", "NovaMachina-Mods_ExNihiloSequentia_AYGoA_nsnvMbtB54W0q1"
    }
}
```

**Comment by friendlyhj** [comment]
But the previous code is literally it.
https://github.com/friendlyhj/ExNihiloSequentia/blob/b5ce3de6917ec8c064f5f5f812116a25cb645f82/build.gradle#L39-L43

**Comment by NovaMachina** [comment]
Sorry. Copied the wrong key: `NovaMachina-Mods_ExNihiloSequentia_AYJwMe16kf6704OXoPeu`

**Comment by remplerus** [comment]
i see the problem of this PR. you have added 7 times the same (duplicated) function. add this to SerializableRecipe and SonarQube shouldn't throw errors.

**Review by remplerus — APPROVED** [review]

**Review by NovaMachina — APPROVED** [review]

**Pull request merged**
